# Generated by Django 4.2.6 on 2023-10-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название мультфильма')),
                ('description', models.TextField(verbose_name='Укажите описание мультфильма')),
                ('image', models.ImageField(upload_to='cartoon/', verbose_name='Загрузите фото')),
                ('genre', models.CharField(choices=[('Приключения', 'Приключения'), ('Комедия', 'Комедия'), ('Драмма', 'Драмма'), ('Мюзикл', 'Мюзикл'), ('Детектив', 'Детектив')], max_length=100, verbose_name='Укадите жанр')),
                ('director', models.CharField(max_length=100, verbose_name='Укажите режиссера')),
                ('cost', models.PositiveIntegerField(verbose_name='Укажите цену')),
                ('trailer', models.URLField(blank=True, verbose_name='Укажите трейлер')),
            ],
        ),
    ]
