# Generated by Django 4.2.6 on 2023-10-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disney',
            name='year',
            field=models.DateField(null=True, verbose_name='Укажите год выпуска мультфильма'),
        ),
    ]
